version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start pedt-etl
    env_file:
      - .env
    build:
      context: .
    environment:
      USER_CODE_PATH: /home/src/pedt-etl
      ENV: dev
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
